import { Button, Card, CardActions, CardContent, CardMedia, Grid, Typography } from '@mui/material'
import { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import http from '../http'
import { Product } from '../model'

interface ProductListPageProps {
  products: Product[]
}

const ProductsListPage: NextPage<ProductListPageProps> = ({products}) => {
  return (
    <div>
      <Head>
        <title>Listagem de Produtos</title>
        {/* <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <Typography component="h1" variant="h3" color="textPrimary" gutterBottom>
        Produtos
      </Typography>
      <Grid container spacing={4}>  
        {
          products.map((product, index) => (
            <Grid key={index} item xs={12} sm={6} md={4}>
              <Card>
                <CardMedia style={{ paddingTop: "56%" }} image={product.image_url}/>
                <CardContent>
                  <Typography gutterBottom variant="h5" component="h2">
                    {product.name}
                  </Typography>
                </CardContent>
                <CardActions>
                  <Link href="/products/[slug]" as={`/products/${product.slug}`} passHref>
                    <Button size="small" color="primary" component="a">Detalhes</Button>
                  </Link>
                </CardActions>
              </Card>
            </Grid>
          ))
        }
      </Grid>
    </div>
  )
}

export default ProductsListPage;

export const getServerSideProps: GetServerSideProps<ProductListPageProps> = async (context) => {
  const {data: products} = await http.get("products")

  return {
    props: {
      products,
    },
  };
}